<a href="https://colab.research.google.com/github/ARAN-ai-python/UsedcarValuePrediction_AI/blob/main/jupyter%20notebook/4.%E4%B8%AD%E5%8F%A4%E8%BB%8A%E4%BE%A1%E6%A0%BC%E4%BA%88%E6%B8%ACAI(%E4%BE%A1%E6%A0%BC_com)_%E3%83%87%E3%83%BC%E3%82%BF%E5%89%8D%E5%87%A6%E7%90%86%E6%A4%9C%E8%A8%8E2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#中古車価格予測AI(価格.com)_データ前処理検討2で検討した関数をimportする
#kkkcom_preprocessing_over(df)
#kkkcom_preprocessing_under(df)を作っていく

#from ipynb.fs.full.AI_com import page_preprocessing
%run ./UsedCar_functions.ipynb
import_test()

All Functions Imported!


In [ ]:
import numpy as np
import pandas as pd
import re

#pandasのデータフレームの行・列表示制限を解除
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

#numpyの表示数制限を解除
np.set_printoptions(threshold=np.inf)


df = pd.read_pickle('Car_Bigdata_Merged.pickle').drop_duplicates()
#kkkcom_preprocessing_over(df)
print(len(df))
df.head(10)

56590


ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06  修復歴なし    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07  修復歴なし    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01  修復歴なし    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    ○      −   −   

                                                  保証 ミッション 駆動方式     排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT  4WD   660cc  5ドア   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT  4WD   660cc  5ドア   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...    AT  4WD  2200cc  5ドア   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...   CVT  4WD   660cc  5ドア   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...   CVT  4WD   660cc  5ドア   

  乗車定員     燃料   ハンドル      車台番号    記録簿 リサイクル料                 整備  \
0   4名   ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別              法定整備付   
1   4名   ガソリン  右ハンドル  786（下3桁）  記録簿あり    リ済別              法定整備付   
2   4名   ガソリン  右ハンドル  475（下3桁）  記録簿あり    リ済別              法定整備付   
3   4名   ガソリン  右ハンドル  583（下3桁）           リ済別             法定整備なし   
4   4名    その他  右ハンドル  892（下3桁）           リ済別             法定整備なし   
5   4名   ガソリン  右ハンドル  594（下3桁）           リ済別              法定整備付   
6   5名  ディーゼル  右ハンドル  654（下3桁）           リ済込             法定整備なし   
7   4名    その他  右ハンドル  641（下3桁）           リ済別  法定整備別（整備費19,800円）   
8   4名   ガソリン  右ハンドル  656（下3桁）  記録簿あり    リ済別              法定整備付   
9   4名    その他  右ハンドル  544（下3桁）           リ済別             法定整備なし   

                              ID車両(グー鑑定)         全長         全幅         全高  \
0                                                                           
1                                         3,395mm※1  1,475mm※1  1,655mm※1   
2                                                                           
3  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）  3,395mm※1  1,475mm※1  1,815mm※1   
4  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）  3,395mm※1  1,475mm※1  1,785mm※1   
5                                         3,395mm※1  1,475mm※1  1,630mm※1   
6                                         4,545mm※1  1,840mm※1  1,690mm※1   
7                                         3,395mm※1  1,475mm※1  1,680mm※1   
8  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-22）  3,395mm※1  1,475mm※1  1,630mm※1   
9                                         3,395mm※1  1,475mm※1  1,680mm※1   

        車両

## ミッション

In [ ]:
df_mission = df.copy()
df_mission['ミッション'].value_counts()

CVT    39543
AT     14259
MT      2768
          20
Name: ミッション, dtype: int64

In [ ]:
df_mission[df_mission['ミッション']=='']
#ワゴンＲ ＨＹＢＲＩＤ　ＦＸ = CVT
#タント Ｘ　ＳＡ = CVT
#アルト Ｌ = CVT
#ムーヴ Ｌ　ＳＡ３ = CVT
#スペーシア = CVT
#ハスラー = CVT
#ルークス Ｘ = CVT
#ＱＸ８０ プロアクティブ = AT
#ピクシスバン クルーズ　ＳＡＩＩＩ = AT
#ジープ・チェロキー = AT
#Ｎ−ＶＡＮ＋スタイル ファン・ホンダセンシング = MT
#パナメーラ ＧＴＳ = MT

ページ                       車名     価格            総額  \
2820   24932962              ワゴンＲ ＨＹＢＲＩＤ  119.9  （総額 134.9万円）   
2878   25100992                    タント Ｘ  139.9  （総額 155.0万円）   
2879   25096788                  ワゴンＲ ＦＡ  109.9  （総額 125.0万円）   
2880   24932971              ワゴンＲ ＨＹＢＲＩＤ  119.9  （総額 135.0万円）   
3163   24932924                    アルト Ｌ   79.9   （総額 95.0万円）   
3173   24932964              ワゴンＲ ＨＹＢＲＩＤ  109.9  （総額 125.0万円）   
3174   24932941                    ムーヴ Ｌ  109.9  （総額 125.0万円）   
3175   24932940       ワゴンＲスティングレー ＨＹＢＲＩＤ  129.9  （総額 144.9万円）   
3176   24932926         スペーシアカスタム ＨＹＢＲＩＤ  169.9  （総額 185.0万円）   
3215   24940348              ワゴンＲ ＨＹＢＲＩＤ  109.9  （総額 125.0万円）   
10342  26937102             ハスラー ハイブリッドＧ  132.8  （総額 138.7万円）   
11778  26471899                パナメーラ ＧＴＳ     応談                 
13069  24613617             ＱＸ８０ プロアクティブ  989.0                 
14282  26761714              ピクシスバン クルーズ  117.0  （総額 122.6万円）   
18642  26937090                   ルークス Ｘ  142.8  （総額 145.0万円）   
41439  27098978      ジープ・チェロキー Ｔｒａｉｌｈａｗｋ  350.0  （総額 365.0万円）   
47568  26741874  Ｎ−ＶＡＮ＋スタイル ファン・ホンダセンシング  139.9  （総額 150.3万円）   
58941  27157001         ヤリスクロス １．５ＨＹＢＲＩＤ  259.8  （総額 275.8万円）   
58942  27157000         ヤリスクロス １．５ＨＹＢＲＩＤ  259.8  （総額 275.8万円）   
59688  27156998               クラウン ２．５ＨＶ  448.0  （総額 464.2万円）   

                      色            年式    走行距離    地域       車検    修復歴 未使用車  \
2820              アイボリー  令和2年(2020年)   0.2万km   青森県  2023/02  修復歴なし    −   
2878               ブラック  令和2年(2020年)   0.3万km   青森県  2023/03  修復歴なし    −   
2879               ブラック  令和2年(2020年)   0.3万km   青森県  2023/02  修復歴なし    −   
2880               ホワイト  令和2年(2020年)   0.3万km   青森県  2023/01  修復歴なし    −   
3163                ブルー  令和元年(2019年)   0.2万km   青森県  2022/10  修復歴なし    −   
3173               Ｂブルー  令和元年(2019年)   0.3万km   青森県  2022/06  修復歴なし    −   
3174               シルバー  令和元年(2019年)   0.3万km   青森県  2022/09  修復歴なし    −   
3175               シルバー  令和元年(2019年)   0.3万km   青森県  2022/05  修復歴なし    −   
3176               ブラック  令和元年(2019年)   0.3万km   青森県  2022/11  修復歴なし    −   
3215                ブルー  令和元年(2019年)   0.5万km   青森県  2022/05  修復歴なし    −   
10342             オフブルー  令和3年(2021年)      5km   群馬県  2024/03  修復歴なし    −   
11778              ブラック  令和3年(2021年)   0.2万km   東京都  2024/02  修復歴なし    −   
13069       ムーンストーンホワイト  令和3年(2021年)        −   埼玉県    新車未登録  修復歴なし    −   
14282          パールホワイト３  令和2年(2020年)    135km  神奈川県  2022/05  修復歴なし    −   
18642             アイボリー  令和2年(2020年)      6km   群馬県  2023/12  修復歴なし    ○   
41439  ＢＲＩＧＨＴ　ＷＨＩＴＥ　Ｃ／Ｃ  令和元年(2019年)    300km  和歌山県  2022/07  修復歴なし    −   
47568               ガンＭ  令和2年(2020年)   0.2万km   広島県  2022/09  修復歴なし    −   
58941       レッドマイカ／ブラック  令和3年(2021年)     20km   長崎県  2024/07  修復歴なし    −   
58942          パール／ブラック  令和3年(2021年)     20km   長崎県  2024/07  修復歴なし    −   
59688               パール  令和2年(2020年)   1.5万km   長崎県  2023/03  修復歴なし    −   

      ワンオーナー 禁煙車                                                 保証 ミッション  \
2820       −   −                                            販売店保証なし         
2878       −   −                                            販売店保証なし         
2879       −   −                                            販売店保証なし         
2880       −   −                                            販売店保証なし         
3163       −   −                                            販売店保証なし         
3173       −   −                                            販売店保証なし         
3174       −   −                                            販売店保証なし         
3175       −   −                                            販売店保証なし         
3176       −   −                                            販売店保証なし         
3215       −   −                                            販売店保証なし         
10342      −   −                                            販売店保証なし         
11778      ○   −  販売店保証付(無料保証 期限:2024年2月 距離:無制限 ※いずれかの条件に達するまで保証...         
13069      −   −  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km 

In [ ]:
#車名を使うならname_preprocessingの前にやらないとね
names = [("ワゴンＲ","CVT"),("タント Ｘ　ＳＡ","CVT"),("アルト Ｌ","CVT"),("ムーヴ Ｌ","CVT"),("スペーシア","CVT"),("ハスラー","CVT"),("ルークス Ｘ","CVT")
         ,("ＱＸ８０ プロアクティブ","AT"),("ピクシスバン クルーズ","AT"),("ジープ・チェロキー","AT")
         ,("パナメーラ ＧＴＳ","MT"),("Ｎ−ＶＡＮ＋スタイル","MT")]
for car,mission in names:
    #print(car,mission)
    #andだと上手くいかず、&だと大丈夫
    df_mission['ミッション'][(df_mission['ミッション']=='') & (df_mission['車名'].str.contains(car))] = mission

df_mission['ミッション'].value_counts()

CVT    39554
AT     14262
MT      2770
           4
Name: ミッション, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE_mission = LabelEncoder()
LE_mission.fit(df_mission['ミッション'])
df_mission['ミッション'] = LE_mission.transform(df_mission['ミッション'])
print(LE_mission.classes_)
display(df_mission.head(10))

['' 'AT' 'CVT' 'MT']


ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06  修復歴なし    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07  修復歴なし    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01  修復歴なし    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    ○      −   −   

                                                  保証  ミッション 駆動方式     排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2  4WD   660cc  5ドア   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2  4WD   660cc  5ドア   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...      1  4WD  2200cc  5ドア   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...      2  4WD   660cc  5ドア   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...      2  4WD   660cc  5ドア   

  乗車定員     燃料   ハンドル      車台番号    記録簿 リサイクル料                 整備  \
0   4名   ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別              法定整備付   
1   4名   ガソリン  右ハンドル  786（下3桁）  記録簿あり    リ済別              法定整備付   
2   4名   ガソリン  右ハンドル  475（下3桁）  記録簿あり    リ済別              法定整備付   
3   4名   ガソリン  右ハンドル  583（下3桁）           リ済別             法定整備なし   
4   4名    その他  右ハンドル  892（下3桁）           リ済別             法定整備なし   
5   4名   ガソリン  右ハンドル  594（下3桁）           リ済別              法定整備付   
6   5名  ディーゼル  右ハンドル  654（下3桁）           リ済込             法定整備なし   
7   4名    その他  右ハンドル  641（下3桁）           リ済別  法定整備別（整備費19,800円）   
8   4名   ガソリン  右ハンドル  656（下3桁）  記録簿あり    リ済別              法定整備付   
9   4名    その他  右ハンドル  544（下3桁）           リ済別             法定整備なし   

                              ID車両(グー鑑定)         全長         全幅         全高  \
0                                                                           
1                                         3,395mm※1  1,475mm※1  1,655mm※1   
2                                                                           
3  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）  3,395mm※1  1,475mm※1  1,815mm※1   
4  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）  3,395mm※1  1,475mm※1  1,785mm※1   
5                                         3,395mm※1  1,475mm※1  1,630mm※1   
6                                         4,545mm※1  1,840mm※1  1,690mm※1   
7                                         3,395mm※1  1,475mm※1  1,680mm※1   
8  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-22）  3,395mm※1  1,475mm※1  1,630mm※1   
9                                         3,395mm※1  1,475mm※1  1,680mm※1   


In [ ]:
def mission_preprocessing(df_mission):
    names = [("ワゴンＲ","CVT"),("タント Ｘ　ＳＡ","CVT"),("アルト Ｌ","CVT"),("ムーヴ Ｌ","CVT"),("スペーシア","CVT"),("ハスラー","CVT"),("ルークス Ｘ","CVT")
             ,("ＱＸ８０ プロアクティブ","AT"),("ピクシスバン クルーズ","AT"),("ジープ・チェロキー","AT")
             ,("パナメーラ ＧＴＳ","MT"),("Ｎ−ＶＡＮ＋スタイル","MT")]
    for car,mission in names:
        df_mission['ミッション'][(df_mission['ミッション']=='') & (df_mission['車名'].str.contains(car))] = mission
        
    global LE_mission
    LE_mission = LabelEncoder()
    LE_mission.fit(df_mission['ミッション'])
    df_mission['ミッション'] = LE_mission.transform(df_mission['ミッション'])
    

In [ ]:
#テスト
df_mission = df.copy()
mission_preprocessing(df_mission)
display(df_mission.head(10))

ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06  修復歴なし    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07  修復歴なし    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01  修復歴なし    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    ○      −   −   

                                                  保証  ミッション 駆動方式     排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2  4WD   660cc  5ドア   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2  4WD   660cc  5ドア   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...      1  4WD  2200cc  5ドア   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...      2  4WD   660cc  5ドア   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2  4WD   660cc  5ドア   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...      2  4WD   660cc  5ドア   

  乗車定員     燃料   ハンドル      車台番号    記録簿 リサイクル料                 整備  \
0   4名   ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別              法定整備付   
1   4名   ガソリン  右ハンドル  786（下3桁）  記録簿あり    リ済別              法定整備付   
2   4名   ガソリン  右ハンドル  475（下3桁）  記録簿あり    リ済別              法定整備付   
3   4名   ガソリン  右ハンドル  583（下3桁）           リ済別             法定整備なし   
4   4名    その他  右ハンドル  892（下3桁）           リ済別             法定整備なし   
5   4名   ガソリン  右ハンドル  594（下3桁）           リ済別              法定整備付   
6   5名  ディーゼル  右ハンドル  654（下3桁）           リ済込             法定整備なし   
7   4名    その他  右ハンドル  641（下3桁）           リ済別  法定整備別（整備費19,800円）   
8   4名   ガソリン  右ハンドル  656（下3桁）  記録簿あり    リ済別              法定整備付   
9   4名    その他  右ハンドル  544（下3桁）           リ済別             法定整備なし   

                              ID車両(グー鑑定)         全長         全幅         全高  \
0                                                                           
1                                         3,395mm※1  1,475mm※1  1,655mm※1   
2                                                                           
3  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）  3,395mm※1  1,475mm※1  1,815mm※1   
4  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）  3,395mm※1  1,475mm※1  1,785mm※1   
5                                         3,395mm※1  1,475mm※1  1,630mm※1   
6                                         4,545mm※1  1,840mm※1  1,690mm※1   
7                                         3,395mm※1  1,475mm※1  1,680mm※1   
8  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-22）  3,395mm※1  1,475mm※1  1,630mm※1   
9                                         3,395mm※1  1,475mm※1  1,680mm※1   


## 駆動方式

In [ ]:
df_drive = df.copy()
df_drive['駆動方式'].value_counts()

2WD    43241
4WD    13349
Name: 駆動方式, dtype: int64

In [ ]:
#先頭の数字だけを切り出す
df_drive['駆動方式'] = df_drive['駆動方式'].map(lambda x : x[:1])
df_drive['駆動方式'] = df_drive['駆動方式'].astype('int')

print(df_drive['駆動方式'].dtypes)
df_drive['駆動方式'].value_counts()

int64


2    43241
4    13349
Name: 駆動方式, dtype: int64

In [ ]:
def drive_preprocessing(df_drive):
    df_drive['駆動方式'] = df_drive['駆動方式'].map(lambda x : x[:1])
    df_drive['駆動方式'] = df_drive['駆動方式'].astype('int')

In [ ]:
#テスト
df_drive = df.copy()
drive_preprocessing(df_drive)
print(df_drive['駆動方式'].unique())
df_drive.head(10)

[4 2]


ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06  修復歴なし    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07  修復歴なし    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01  修復歴なし    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    ○      −   −   

                                                  保証 ミッション  駆動方式     排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT     4   660cc  5ドア   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT     4   660cc  5ドア   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT     4   660cc  5ドア   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT     4   660cc  5ドア   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT     4   660cc  5ドア   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT     4   660cc  5ドア   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...    AT     4  2200cc  5ドア   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...   CVT     4   660cc  5ドア   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT     4   660cc  5ドア   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...   CVT     4   660cc  5ドア   

  乗車定員     燃料   ハンドル      車台番号    記録簿 リサイクル料                 整備  \
0   4名   ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別              法定整備付   
1   4名   ガソリン  右ハンドル  786（下3桁）  記録簿あり    リ済別              法定整備付   
2   4名   ガソリン  右ハンドル  475（下3桁）  記録簿あり    リ済別              法定整備付   
3   4名   ガソリン  右ハンドル  583（下3桁）           リ済別             法定整備なし   
4   4名    その他  右ハンドル  892（下3桁）           リ済別             法定整備なし   
5   4名   ガソリン  右ハンドル  594（下3桁）           リ済別              法定整備付   
6   5名  ディーゼル  右ハンドル  654（下3桁）           リ済込             法定整備なし   
7   4名    その他  右ハンドル  641（下3桁）           リ済別  法定整備別（整備費19,800円）   
8   4名   ガソリン  右ハンドル  656（下3桁）  記録簿あり    リ済別              法定整備付   
9   4名    その他  右ハンドル  544（下3桁）           リ済別             法定整備なし   

                              ID車両(グー鑑定)         全長         全幅         全高  \
0                                                                           
1                                         3,395mm※1  1,475mm※1  1,655mm※1   
2                                                                           
3  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）  3,395mm※1  1,475mm※1  1,815mm※1   
4  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）  3,395mm※1  1,475mm※1  1,785mm※1   
5                                         3,395mm※1  1,475mm※1  1,630mm※1   
6                                         4,545mm※1  1,840mm※1  1,690mm※1   
7                                         3,395mm※1  1,475mm※1  1,680mm※1   
8  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-22）  3,395mm※1  1,475mm※1  1,630mm※1   
9                                         3,395mm※1  1,475mm※1  1,680mm※1   


## 排気量

In [ ]:
df_displacement = df.copy()
df_displacement.排気量.value_counts()
#先にccを取り除こう
#空欄は0に置換しよう

660cc       35645
2000cc       4180
1500cc       3492
1000cc       2730
1200cc       2584
2500cc       1520
1800cc       1333
2200cc        693
2700cc        597
2800cc        575
3000cc        541
1300cc        536
1400cc        396
2400cc        319
1600cc        297
4000cc        156
              152
3500cc        135
3600cc        111
2300cc         68
650cc          62
900cc          44
990cc          38
5700cc         29
2990cc         24
7500cc         23
6200cc         21
4600cc         18
3900cc         16
1900cc         16
5000cc         16
5200cc         16
4400cc         15
3800cc         13
3700cc         12
2900cc         12
7540cc         10
9900cc          9
6400cc          8
5120cc          8
2100cc          7
5100cc          6
10670cc         5
10700cc         5
2434cc          4
6500cc          4
125cc           4
3200cc          4
4700cc          4
12900cc         4
4200cc          4
5300cc          3
6600cc          3
8860cc          3
996cc           3
10830cc   

In [ ]:
#先にccを取り除こう
df_displacement['排気量'] = df_displacement['排気量'].map(lambda x : x[:-2])
df_displacement.排気量.unique()

array(['660', '2200', '2500', '2800', '1200', '1500', '2000', '650',
       '1000', '1400', '1800', '2700', '2400', '3000', '1600', '1300',
       '900', '4400', '3600', '6200', '4000', '', '123600', '5700',
       '8860', '8200', '3800', '2990', '990', '5120', '2300', '4600',
       '1900', '2100', '3500', '7500', '4200', '11000', '5200', '1647',
       '2343', '1826', '2434', '658', '3700', '9900', '10700', '12900',
       '5100', '8900', '5000', '1120', '6400', '666', '3900', '996',
       '6500', '6000', '5300', '5600', '4800', '7540', '10670', '3400',
       '5400', '2900', '4300', '8600', '600', '8', '1642', '59', '3200',
       '4460', '10830', '5500', '9800', '4700', '125', '6600', '1860',
       '4500', '85', '2924', '1949', '1240', '2750', '9830', '3300',
       '5190', '51230', '50', '150', '200', '6700', '500', '360', '1'],
      dtype=object)

In [ ]:
#空欄は0に置換しよう
df_displacement['排気量'].replace('', '0', inplace=True)
df_displacement['排気量'].unique()

array(['660', '2200', '2500', '2800', '1200', '1500', '2000', '650',
       '1000', '1400', '1800', '2700', '2400', '3000', '1600', '1300',
       '900', '4400', '3600', '6200', '4000', '0', '123600', '5700',
       '8860', '8200', '3800', '2990', '990', '5120', '2300', '4600',
       '1900', '2100', '3500', '7500', '4200', '11000', '5200', '1647',
       '2343', '1826', '2434', '658', '3700', '9900', '10700', '12900',
       '5100', '8900', '5000', '1120', '6400', '666', '3900', '996',
       '6500', '6000', '5300', '5600', '4800', '7540', '10670', '3400',
       '5400', '2900', '4300', '8600', '600', '8', '1642', '59', '3200',
       '4460', '10830', '5500', '9800', '4700', '125', '6600', '1860',
       '4500', '85', '2924', '1949', '1240', '2750', '9830', '3300',
       '5190', '51230', '50', '150', '200', '6700', '500', '360', '1'],
      dtype=object)

In [ ]:
#int型に変換
df_displacement['排気量'] = df_displacement['排気量'].astype('int')
df_displacement['排気量'].dtypes

dtype('int64')

In [ ]:
def displacement_preprocessing(df_displacement):
    df_displacement['排気量'] = df_displacement['排気量'].map(lambda x : x[:-2])
    df_displacement['排気量'].replace('', '0', inplace=True)
    df_displacement['排気量'] = df_displacement['排気量'].astype('int')

In [ ]:
#テスト
df_displacement = df.copy()
displacement_preprocessing(df_displacement)
print(df_displacement['排気量'].dtypes)
df_displacement['排気量'].unique()

int64


array([   660,   2200,   2500,   2800,   1200,   1500,   2000,    650,
         1000,   1400,   1800,   2700,   2400,   3000,   1600,   1300,
          900,   4400,   3600,   6200,   4000,      0, 123600,   5700,
         8860,   8200,   3800,   2990,    990,   5120,   2300,   4600,
         1900,   2100,   3500,   7500,   4200,  11000,   5200,   1647,
         2343,   1826,   2434,    658,   3700,   9900,  10700,  12900,
         5100,   8900,   5000,   1120,   6400,    666,   3900,    996,
         6500,   6000,   5300,   5600,   4800,   7540,  10670,   3400,
         5400,   2900,   4300,   8600,    600,      8,   1642,     59,
         3200,   4460,  10830,   5500,   9800,   4700,    125,   6600,
         1860,   4500,     85,   2924,   1949,   1240,   2750,   9830,
         3300,   5190,  51230,     50,    150,    200,   6700,    500,
          360,      1])

## ドア数

In [ ]:
df_door = df.copy()
df_door['ドア数'].value_counts()

5ドア    50791
2ドア     2907
4ドア     1900
3ドア      880
         112
Name: ドア数, dtype: int64

In [ ]:
#'ドア'を除去する
df_door['ドア数'] = df_door['ドア数'].map(lambda x :x[:-2])
df_door['ドア数'].unique()

array(['5', '2', '3', '4', ''], dtype=object)

In [ ]:
#欠損値に付き合っている程暇ではないので、ここは0で置換する
df_door['ドア数'].replace('', '0', inplace=True)
df_door['ドア数'].unique()

array(['5', '2', '3', '4', '0'], dtype=object)

In [ ]:
#int型にする
df_door['ドア数'] = df_door['ドア数'].astype('int')
df_door['ドア数'].dtypes

dtype('int64')

In [ ]:
def door_preprocessing(df_door):
    df_door['ドア数'] = df_door['ドア数'].map(lambda x :x[:-2])
    df_door['ドア数'].replace('', '0', inplace=True)
    df_door['ドア数'] = df_door['ドア数'].astype('int')

In [ ]:
#テスト
df_door = df.copy()
door_preprocessing(df_door)
print(df_door['ドア数'].dtypes)
df_door['ドア数'].value_counts()

int64


5    50791
2     2907
4     1900
3      880
0      112
Name: ドア数, dtype: int64

## 乗車定員

In [ ]:
df_capacity = df.copy()
df_capacity['乗車定員'].value_counts()

4名       29660
5名       13361
          7734
7名        2359
2名        1652
8名         827
6名         464
3名         260
10名        238
1名          20
16名以上        9
9名           4
14名          2
Name: 乗車定員, dtype: int64

In [ ]:
#"名","以","上"を除去する
df_capacity['乗車定員'] = df_capacity['乗車定員'].str.translate(str.maketrans({"名":"","以":"","上":""}))
df_capacity['乗車定員'].unique()

array(['4', '5', '7', '', '6', '2', '8', '3', '10', '1', '16', '14', '9'],
      dtype=object)

In [ ]:
df_capacity['乗車定員'][df_capacity['乗車定員']==''] = 0
df_capacity['乗車定員'].unique()

array(['4', '5', '7', 0, '6', '2', '8', '3', '10', '1', '16', '14', '9'],
      dtype=object)

In [ ]:
df_capacity['乗車定員'] = df_capacity['乗車定員'].astype('int')
df_capacity['乗車定員'].dtypes

dtype('int64')

In [ ]:
def capacity_preprocessing(df_capacity):
    df_capacity['乗車定員'] = df_capacity['乗車定員'].str.translate(str.maketrans({"名":"","以":"","上":""}))
    df_capacity['乗車定員'][df_capacity['乗車定員']==''] = 0
    df_capacity['乗車定員'] = df_capacity['乗車定員'].astype('int')

In [ ]:
#テスト
df_capacity = df.copy()
capacity_preprocessing(df_capacity)
print(df_capacity['乗車定員'].dtypes)
df_capacity['乗車定員'].value_counts()

int64


4     29660
5     13361
0      7734
7      2359
2      1652
8       827
6       464
3       260
10      238
1        20
16        9
9         4
14        2
Name: 乗車定員, dtype: int64

## 燃料

In [ ]:
df_fuel = df.copy()
df_fuel['燃料'].value_counts()

ガソリン     38703
その他      14776
ディーゼル     3111
Name: 燃料, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE_fuel = LabelEncoder()
LE_fuel.fit(df_fuel['燃料'])
df_fuel['燃料'] = LE_fuel.transform(df_fuel['燃料'])
print(LE_fuel.classes_)
df_fuel['燃料'].unique()

['その他' 'ガソリン' 'ディーゼル']


array([1, 0, 2])

In [ ]:
def fuel_preprocessing(df_fuel):
    from sklearn.preprocessing import LabelEncoder
    global LE_fuel
    LE_fuel = LabelEncoder()
    LE_fuel.fit(df_fuel['燃料'])
    df_fuel['燃料'] = LE_fuel.transform(df_fuel['燃料'])

In [ ]:
#テスト
df_fuel = df.copy()
fuel_preprocessing(df_fuel)
print(LE_fuel.classes_)
df_fuel['燃料'].value_counts()

['その他' 'ガソリン' 'ディーゼル']


1    38703
0    14776
2     3111
Name: 燃料, dtype: int64

## ハンドル

In [ ]:
df_handle = df.copy()
df_handle['ハンドル'].value_counts()

右ハンドル    56294
左ハンドル      296
Name: ハンドル, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE_handle = LabelEncoder()
LE_handle.fit(df_handle['ハンドル'])
df_handle['ハンドル'] = LE_handle.transform(df_handle['ハンドル'])
print(LE_handle.classes_)
df_handle['ハンドル'].unique()

['右ハンドル' '左ハンドル']


array([0, 1])

In [ ]:
def handle_preprocessing(df_handle):
    from sklearn.preprocessing import LabelEncoder
    global LE_handle
    LE_handle = LabelEncoder()
    LE_handle.fit(df_handle['ハンドル'])
    df_handle['ハンドル'] = LE_handle.transform(df_handle['ハンドル'])

In [ ]:
#テスト
df_handle = df.copy()
handle_preprocessing(df_handle)
print(LE_handle.classes_)
df_handle['ハンドル'].unique()

['右ハンドル' '左ハンドル']


array([0, 1])

## 車台番号

In [ ]:
df_number = df.copy()
df_number['車台番号'].value_counts()

488（下3桁）    84
565（下3桁）    79
203（下3桁）    79
162（下3桁）    76
694（下3桁）    75
392（下3桁）    74
442（下3桁）    74
741（下3桁）    74
100（下3桁）    74
010（下3桁）    73
394（下3桁）    73
562（下3桁）    73
153（下3桁）    73
320（下3桁）    73
475（下3桁）    73
871（下3桁）    72
702（下3桁）    72
323（下3桁）    72
361（下3桁）    72
737（下3桁）    72
106（下3桁）    72
403（下3桁）    72
542（下3桁）    72
604（下3桁）    72
164（下3桁）    72
575（下3桁）    72
566（下3桁）    72
288（下3桁）    71
212（下3桁）    71
130（下3桁）    71
287（下3桁）    71
502（下3桁）    71
377（下3桁）    71
171（下3桁）    71
219（下3桁）    71
158（下3桁）    71
349（下3桁）    71
550（下3桁）    71
944（下3桁）    71
462（下3桁）    70
292（下3桁）    70
992（下3桁）    70
941（下3桁）    70
105（下3桁）    70
450（下3桁）    70
257（下3桁）    69
448（下3桁）    69
242（下3桁）    69
080（下3桁）    69
473（下3桁）    69
499（下3桁）    69
398（下3桁）    69
718（下3桁）    69
141（下3桁）    69
693（下3桁）    69
553（下3桁）    69
823（下3桁）    69
538（下3桁）    69
767（下3桁）    69
975（下3桁）    69
529（下3桁）    68
922（下3桁）    68
876（下3桁）    68
357（下3桁）    68
355（下3桁）    68
163（下3桁）    68
099（下3桁）  

In [ ]:
#(下3桁)を削除
df_number['車台番号'] = df_number['車台番号'].map(lambda x : x.replace('（下3桁）', ''))
df_number['車台番号'].unique()

array(['403', '786', '475', '583', '892', '594', '654', '641', '656',
       '544', '945', '671', '374', '330', '258', '684', '018', '115',
       '449', '336', '818', '063', '341', '988', '091', '214', '570',
       '382', '532', '601', '280', '463', '245', '801', '724', '773',
       '593', '670', '986', '603', '081', '262', '027', '112', '373',
       '519', '926', '660', '143', '240', '462', '917', '803', '814',
       '077', '598', '929', '453', '578', '802', '906', '668', '823',
       '015', '013', '659', '690', '878', '269', '568', '753', '298',
       '499', '507', '316', '866', '165', '193', '901', '243', '811',
       '652', '129', '211', '083', '139', '643', '078', '126', '451',
       '352', '357', '172', '089', '897', '931', '923', '084', '928',
       '017', '989', '073', '136', '779', '723', '924', '483', '648',
       '113', '194', '538', '950', '972', '195', '479', '289', '484',
       '448', '871', '938', '168', '135', '460', '769', '061', '249',
       '973', '346',

In [ ]:
#(下3桁)と同時に4M-等を削除
nums = {'（下3桁）':""
        ,'BVF':"-1"
        ,'4M-':"-2"
        ,'36L':"-3"
        ,'40A':"-4"
        ,'25-':"-5"
        ,'5S-':"-6"
        ,'RF-':"-7"
        ,'KL-':"-8"
        ,'FF-':"-9"
       }
for num in nums:
    print(num)
    df_number['車台番号'] = df_number['車台番号'].map(lambda x : x.replace(num, nums[num]))
df_number['車台番号'].unique()

（下3桁）
BVF
4M-
36L
40A
25-
5S-
RF-
KL-
FF-


array(['403', '786', '475', '583', '892', '594', '654', '641', '656',
       '544', '945', '671', '374', '330', '258', '684', '018', '115',
       '449', '336', '818', '063', '341', '988', '091', '214', '570',
       '382', '532', '601', '280', '463', '245', '801', '724', '773',
       '593', '670', '986', '603', '081', '262', '027', '112', '373',
       '519', '926', '660', '143', '240', '462', '917', '803', '814',
       '077', '598', '929', '453', '578', '802', '906', '668', '823',
       '015', '013', '659', '690', '878', '269', '568', '753', '298',
       '499', '507', '316', '866', '165', '193', '901', '243', '811',
       '652', '129', '211', '083', '139', '643', '078', '126', '451',
       '352', '357', '172', '089', '897', '931', '923', '084', '928',
       '017', '989', '073', '136', '779', '723', '924', '483', '648',
       '113', '194', '538', '950', '972', '195', '479', '289', '484',
       '448', '871', '938', '168', '135', '460', '769', '061', '249',
       '973', '346',

In [ ]:
#dtypeをint型に変換する
df_number['車台番号'] = df_number['車台番号'].astype('int')
print(df_number['車台番号'].dtypes)
df_number['車台番号'].unique()

int64


array([403, 786, 475, 583, 892, 594, 654, 641, 656, 544, 945, 671, 374,
       330, 258, 684,  18, 115, 449, 336, 818,  63, 341, 988,  91, 214,
       570, 382, 532, 601, 280, 463, 245, 801, 724, 773, 593, 670, 986,
       603,  81, 262,  27, 112, 373, 519, 926, 660, 143, 240, 462, 917,
       803, 814,  77, 598, 929, 453, 578, 802, 906, 668, 823,  15,  13,
       659, 690, 878, 269, 568, 753, 298, 499, 507, 316, 866, 165, 193,
       901, 243, 811, 652, 129, 211,  83, 139, 643,  78, 126, 451, 352,
       357, 172,  89, 897, 931, 923,  84, 928,  17, 989,  73, 136, 779,
       723, 924, 483, 648, 113, 194, 538, 950, 972, 195, 479, 289, 484,
       448, 871, 938, 168, 135, 460, 769,  61, 249, 973, 346, 495, 485,
       233, 651, 505, 406, 540, 287, 758, 883, 633, 722, 799, 425, 743,
       762, 822, 555, 838,   5, 371, 759, 535, 205, 554, 715, 885, 428,
       914, 582, 564,  80, 797, 459, 523, 776, 946, 438, 281, 565, 125,
       925, 525, 502, 921, 725, 252, 291, 257, 992, 907,  72, 26

In [ ]:
def number_preprocessing(df_number):
    nums = {'（下3桁）':""
            ,'BVF':"-1"
            ,'4M-':"-2"
            ,'36L':"-3"
            ,'40A':"-4"
            ,'25-':"-5"
            ,'5S-':"-6"
            ,'RF-':"-7"
            ,'KL-':"-8"
            ,'FF-':"-9"
           }
    
    for num in nums:
        df_number['車台番号'] = df_number['車台番号'].map(lambda x : x.replace(num, nums[num]))
        
    df_number['車台番号'] = df_number['車台番号'].astype('int')

In [ ]:
#テスト
df_number = df.copy()
number_preprocessing(df_number)
print(df_number['車台番号'].dtypes)
df_number['車台番号'].unique()

int64


array([403, 786, 475, 583, 892, 594, 654, 641, 656, 544, 945, 671, 374,
       330, 258, 684,  18, 115, 449, 336, 818,  63, 341, 988,  91, 214,
       570, 382, 532, 601, 280, 463, 245, 801, 724, 773, 593, 670, 986,
       603,  81, 262,  27, 112, 373, 519, 926, 660, 143, 240, 462, 917,
       803, 814,  77, 598, 929, 453, 578, 802, 906, 668, 823,  15,  13,
       659, 690, 878, 269, 568, 753, 298, 499, 507, 316, 866, 165, 193,
       901, 243, 811, 652, 129, 211,  83, 139, 643,  78, 126, 451, 352,
       357, 172,  89, 897, 931, 923,  84, 928,  17, 989,  73, 136, 779,
       723, 924, 483, 648, 113, 194, 538, 950, 972, 195, 479, 289, 484,
       448, 871, 938, 168, 135, 460, 769,  61, 249, 973, 346, 495, 485,
       233, 651, 505, 406, 540, 287, 758, 883, 633, 722, 799, 425, 743,
       762, 822, 555, 838,   5, 371, 759, 535, 205, 554, 715, 885, 428,
       914, 582, 564,  80, 797, 459, 523, 776, 946, 438, 281, 565, 125,
       925, 525, 502, 921, 725, 252, 291, 257, 992, 907,  72, 26

## 記録簿

In [ ]:
df_record = df.copy()
df_record.記録簿.value_counts()

         41841
記録簿あり    14749
Name: 記録簿, dtype: int64

In [ ]:
#「記録簿あり」を1に変換する
df_record['記録簿'] = df_record['記録簿'].map(lambda x : 0 if (x=='') else 1)

print(df_record['記録簿'].dtypes)
df_record['記録簿'].unique()

int64


array([1, 0])

In [ ]:
def record_preprocessing(df_record):
    df_record['記録簿'] = df_record['記録簿'].map(lambda x : 0 if (x=='') else 1)

In [ ]:
#テスト
df_record = df.copy()
record_preprocessing(df_record)
df_record['記録簿'].value_counts()

0    41841
1    14749
Name: 記録簿, dtype: int64

## リサイクル料

In [ ]:
df_recycle = df.copy()
df_recycle['リサイクル料'].value_counts()

リ済別    52486
リ済込     3035
リ未      1069
Name: リサイクル料, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE_recycle = LabelEncoder()
LE_recycle.fit(df_recycle['リサイクル料'])
df_recycle['リサイクル料'] = LE_recycle.transform(df_recycle['リサイクル料'])
df_recycle['リサイクル料'].unique()

array([1, 2, 0])

In [ ]:
def recycle_preprocessing(df_recycle):
    from sklearn.preprocessing import LabelEncoder
    global LE_recycle
    LE_recycle = LabelEncoder()
    LE_recycle.fit(df_recycle['リサイクル料'])
    df_recycle['リサイクル料'] = LE_recycle.transform(df_recycle['リサイクル料'])

In [ ]:
#テスト
df_recycle = df.copy()
recycle_preprocessing(df_recycle)
print(LE_recycle.classes_)
df_recycle['リサイクル料'].unique()

['リ未' 'リ済別' 'リ済込']


array([1, 2, 0])

## 整備

In [ ]:
df_maintenance = df.copy()
df_maintenance['整備'].value_counts()

法定整備付                 35020
法定整備なし                17555
法定整備別（整備費16,500円）       452
法定整備別（整備費33,000円）       371
法定整備別（整備費22,000円）       326
法定整備別（整備費38,500円）       244
法定整備別（整備費55,000円）       173
法定整備別（整備費40,370円）       154
法定整備別（整備費27,500円）       129
法定整備別（整備費41,580円）       128
法定整備別（整備費42,746円）       122
法定整備別（整備費13,200円）       104
法定整備別（整備費40,000円）        96
法定整備別（整備費43,780円）        95
法定整備別（整備費49,500円）        95
法定整備別（整備費47,146円）        94
法定整備別（整備費44,000円）        92
法定整備別（整備費30,800円）        81
法定整備別（整備費47,080円）        71
法定整備別（整備費25,000円）        66
法定整備別（整備費19,800円）        62
法定整備別（整備費11,000円）        50
法定整備別（整備費58,080円）        43
法定整備別（整備費49,000円）        41
法定整備別（整備費28,000円）        40
法定整備別（整備費39,000円）        38
法定整備別（整備費66,000円）        31
法定整備別（整備費35,000円）        30
法定整備別（整備費40,700円）        29
法定整備別（整備費69,800円）        29
法定整備別（整備費36,146円）        28
法定整備別（整備費44,800円）        28
法定整備別（整備費60,500円）        27
法定整備別（整備費29,800円）        26
法定整備別（整備費54,800円）        26
法定整備別（整備費12,000円）   

In [ ]:
#整備フラグを作成すべき
#整備フラグが0のやつだけ整備費カラムに金額を入れて特徴量を作りたい

df_maintenance['整備フラグ'] = 0
df_maintenance['整備フラグ'] = df_maintenance['整備フラグ'].mask(df_maintenance['整備']=='法定整備付', 1)
df_maintenance['整備フラグ'] = df_maintenance['整備フラグ'].mask(df_maintenance['整備']=='法定整備なし', 2)

print(df_maintenance['整備フラグ'].unique())
#df_maintenance.head(10)

[1 2 0]


In [ ]:
df_maintenance[df_maintenance['整備']=="法定整備別"]
#0にするか

ページ                  車名     価格 総額                           色  \
56386  26990888                ハスラー  177.8         オフブルーメタリック　ガンメタリック２トーン   
60350  26443518          ハスラー Ｊスタイル  179.8         ピュアホワイトパール　ガンメタリック２トーン   
60353  26316103            ライズ １．０Ｚ  218.9     ブラックマイカメタリック／シャイニングホワイトパール   
60409  26564436  キャリイトラック 金太郎ダンプ４ＷＤ  119.8                       スペリアホワイト   
60410  26310359      キャリイトラック 頑丈ダンプ  135.8                       スペリアホワイト   
60640  26882071     ソリオ １．２ハイブリッドＭＺ  217.8                     ピュアホワイトパール   

                 年式  走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
56386  令和3年(2021年)   10km  熊本県  2024/06  修復歴なし    ○      −   ○   
60350  令和3年(2021年)   10km  熊本県  2024/03  修復歴なし    ○      −   −   
60353  令和3年(2021年)   10km  熊本県  2024/03  修復歴なし    ○      −   ○   
60409  令和3年(2021年)   30km  熊本県  2023/04  修復歴なし    ○      −   −   
60410  令和3年(2021年)   30km  熊本県  2023/03  修復歴なし    ○      −   −   
60640  令和2年(2020年)   10km  熊本県  2023/12  修復歴なし    ○      −   −   

                                                      保証 ミッション 駆動方式     排気量  \
56386  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...   CVT  2WD   660cc   
60350  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...   CVT  2WD   660cc   
60353  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...   CVT  2WD  1000cc   
60409  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...    MT  4WD   650cc   
60410  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...    MT  4WD   660cc   
60640  販売店保証付(無料保証 期間:1ヵ月 距離:1,000km ※いずれかの条件に達するまで保証...   CVT  2WD  1200cc   

       ドア数 乗車定員    燃料   ハンドル      車台番号 記録簿 リサイクル料     整備 ID車両(グー鑑定)  \
56386  5ドア       ガソリン  右ハンドル  821（下3桁）        リ済別  法定整備別              
60350  5ドア   4名   その他  右ハンドル  764（下3桁）        リ済別  法定整備別              
60353  5ドア   5名  ガソリン  右ハンドル  833（下3桁）        リ済別  法定整備別              
60409  2ドア   2名  ガソリン  右ハンドル  616（下3桁）        リ済別  法定整備別              
60410  2ドア   2名  ガソリン  右ハンドル  341（下3桁）        リ済別  法定整備別              
60640  5ドア   5名   その他  右ハンドル  200（下3桁）        リ済別  法定整備別              

              全長         全幅         全高       車両重量          燃費     使用燃料  \
56386                                                                    
60350  3,395mm※1  1,475mm※1  1,680mm※1    820kg※1  30.4km/L※1  レギュラー※1   
60353  3,995mm※1  1,695mm※1  1,620mm※1    980kg※1  22.8km/L※1  レギュラー※1   
60409                                                                    
60410                                                                    
60640  3,790mm※1  1,645mm※1  1,745mm※1  1,000kg※1  22.4km/L※1  レギュラー※1   

                                                   オプション  整備フラグ  
56386  エアコン パワーステアリング パワーウィンドウ カーナビ バックモニターカメラ テレビ キー...      0  
60350  エアコン パワーステアリング パワーウィンドウ カーナビ バックモニターカメラ テレビ キー...      0  
60353  エアコン パワーステアリング パワーウィンドウ バックモニターカメラ テレビ キーレスエント...      0  
60409                        エアコン パワーステアリング ABS アルミホイール       0  
60410                        エアコン パワーステアリング ABS アルミホイール       0  
60640  エアコン パワーステアリング パワーウィンドウ カーナビ バックモニターカメラ テレビ キー...      0

In [ ]:
df_maintenance['整備費'] = 0
df_maintenance['整備費'] = df_maintenance['整備'].map(lambda x : x[9:-2] if ('整備費' in x) else '0')

df_maintenance['整備費'].unique()

array(['0', '19,800', '22,000', '44,000', '28,000', '13,200', '16,500',
       '27,500', '16,800', '55,000', '77,000', '82,500', '66,000',
       '16,200', '11,000', '33,000', '20,900', '38,500', '10,000',
       '12,100', '60,500', '41,580', '36,146', '25,300', '18,000',
       '49,500', '39,800', '88,000', '54,000', '110,000', '165,000',
       '58,000', '50,000', '40,370', '42,746', '74,500', '71,800',
       '58,080', '20,000', '47,146', '43,780', '49,800', '46,200',
       '48,000', '32,400', '47,080', '91,300', '71,280', '76,780',
       '52,800', '100,000', '48,500', '21,600', '53,000', '65,000',
       '30,800', '19,000', '41,800', '132,000', '12,000', '38,000',
       '35,000', '99,800', '25,000', '27,000', '198,000', '99,000',
       '20,440', '49,000', '35,200', '29,700', '158,000', '64,800',
       '43,846', '42,900', '39,000', '44,800', '40,000', '52,580',
       '31,500', '30,000', '59,800', '24,200', '31,900', '28,500',
       '79,800', '15,800', '63,800', '52,646', '29,

In [ ]:
#カンマを取り除いてint型に変換
df_maintenance['整備費'] = df_maintenance['整備費'].str.translate(str.maketrans({",":""}))
print(df_maintenance['整備費'].unique()) #0のデータ型をstrにしないと0がnanになってしまう
df_maintenance['整備費'] = df_maintenance['整備費'].astype('int')

print(df_maintenance['整備費'].dtypes)
df_maintenance['整備費'].unique()

['0' '19800' '22000' '44000' '28000' '13200' '16500' '27500' '16800'
 '55000' '77000' '82500' '66000' '16200' '11000' '33000' '20900' '38500'
 '10000' '12100' '60500' '41580' '36146' '25300' '18000' '49500' '39800'
 '88000' '54000' '110000' '165000' '58000' '50000' '40370' '42746' '74500'
 '71800' '58080' '20000' '47146' '43780' '49800' '46200' '48000' '32400'
 '47080' '91300' '71280' '76780' '52800' '100000' '48500' '21600' '53000'
 '65000' '30800' '19000' '41800' '132000' '12000' '38000' '35000' '99800'
 '25000' '27000' '198000' '99000' '20440' '49000' '35200' '29700' '158000'
 '64800' '43846' '42900' '39000' '44800' '40000' '52580' '31500' '30000'
 '59800' '24200' '31900' '28500' '79800' '15800' '63800' '52646' '29500'
 '35750' '48600' '55800' '37500' '39600' '37800' '66800' '98800' '25800'
 '43800' '54800' '29800' '12300' '53900' '9000' '93800' '36700' '42800'
 '15400' '38800' '40940' '29160' '29161' '69800' '68000' '9900' '31000'
 '60000' '300000' '13000' '12600' '127500' '40700' 

array([     0,  19800,  22000,  44000,  28000,  13200,  16500,  27500,
        16800,  55000,  77000,  82500,  66000,  16200,  11000,  33000,
        20900,  38500,  10000,  12100,  60500,  41580,  36146,  25300,
        18000,  49500,  39800,  88000,  54000, 110000, 165000,  58000,
        50000,  40370,  42746,  74500,  71800,  58080,  20000,  47146,
        43780,  49800,  46200,  48000,  32400,  47080,  91300,  71280,
        76780,  52800, 100000,  48500,  21600,  53000,  65000,  30800,
        19000,  41800, 132000,  12000,  38000,  35000,  99800,  25000,
        27000, 198000,  99000,  20440,  49000,  35200,  29700, 158000,
        64800,  43846,  42900,  39000,  44800,  40000,  52580,  31500,
        30000,  59800,  24200,  31900,  28500,  79800,  15800,  63800,
        52646,  29500,  35750,  48600,  55800,  37500,  39600,  37800,
        66800,  98800,  25800,  43800,  54800,  29800,  12300,  53900,
         9000,  93800,  36700,  42800,  15400,  38800,  40940,  29160,
      

In [ ]:
#整備カラムを削除する
del df_maintenance['整備']
df_maintenance.head(1)

ページ                   車名     価格            総額        色            年式  \
0  27129593  タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）  パールブラック  令和3年(2021年)    

  走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  3km  北海道  2024/01  修復歴なし    −      ○   ○   

                                                  保証 ミッション 駆動方式    排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD  660cc  5ドア   

  乗車定員    燃料   ハンドル      車台番号    記録簿 リサイクル料 ID車両(グー鑑定) 全長 全幅 全高 車両重量 燃費 使用燃料  \
0   4名  ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別                                    

                                               オプション  整備フラグ  整備費  
0  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...      1    0

In [ ]:
def maintenance_preprocessing(df_maintenance):
    df_maintenance['整備フラグ'] = 0
    df_maintenance['整備フラグ'] = df_maintenance['整備フラグ'].mask(df_maintenance['整備']=='法定整備付', 1)
    df_maintenance['整備フラグ'] = df_maintenance['整備フラグ'].mask(df_maintenance['整備']=='法定整備なし', 2)
    
    df_maintenance['整備費'] = 0
    df_maintenance['整備費'] = df_maintenance['整備'].map(lambda x : x[9:-2] if ('整備費' in x) else '0')
    
    df_maintenance['整備費'] = df_maintenance['整備費'].str.translate(str.maketrans({",":""}))
    df_maintenance['整備費'] = df_maintenance['整備費'].astype('int')
    
    del df_maintenance['整備']


In [ ]:
#テスト
df_maintenance = df.copy()
maintenance_preprocessing(df_maintenance)
print(df_maintenance['整備費'].dtypes)
df_maintenance.head(1)

int64


ページ                   車名     価格            総額        色            年式  \
0  27129593  タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）  パールブラック  令和3年(2021年)    

  走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  3km  北海道  2024/01  修復歴なし    −      ○   ○   

                                                  保証 ミッション 駆動方式    排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD  660cc  5ドア   

  乗車定員    燃料   ハンドル      車台番号    記録簿 リサイクル料 ID車両(グー鑑定) 全長 全幅 全高 車両重量 燃費 使用燃料  \
0   4名  ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別                                    

                                               オプション  整備フラグ  整備費  
0  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...      1    0

## ID車両(グー鑑定)

In [ ]:
df_judgement = df.copy()
df_judgement['ID車両(グー鑑定)'].value_counts()
#空白は0で埋める
#外装、内装は1~5の整数
#機関は「正常」以外なかったので、特徴量にしない
#修復歴は無か有のどちらか
#修復歴が有の場合、軽度・中度・重度のランク付がなされている
#鑑定日は全ての修復歴に入っている
#外装、内装、修復歴、鑑定日で分けちゃう？

                                            45822
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-23）         191
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-29）         169
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-14）         167
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-19）         162
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-16）         159
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-08）         152
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-28）         145
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）         140
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-12）         139
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）         136
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-13）         132
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-28）         125
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-09）         122
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-26）         120
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-05）         118
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-02）         117
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-21）         116
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-27）         115
外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-18）         114


In [ ]:
#修復歴を作成する(空白は0で埋める)
#無->1、有(軽度)->2、有(中度)->3、有(重度)->4
df_judgement['修復歴'] = 0
#df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains('無'), 1)
#df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains('軽度'), 2)
#df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains('中度'), 3)
#df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains('重度'), 4)

for num, name in enumerate(['無','軽度','中度','重度']):
    df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains(name), num+1)

print(df_judgement['修復歴'].unique())
df_judgement['修復歴'].value_counts()

[0 1 3 2 4]


0    45822
1    10655
2       87
3       25
4        1
Name: 修復歴, dtype: int64

In [ ]:
#外装・内装カラムを作成
df_judgement['外装'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : int(x[3:4]) if ('鑑定日' in x) else 0)
print("外装：",df_judgement['外装'].unique())

df_judgement['内装'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : int(x[8:9]) if ('鑑定日' in x) else 0)
print("内装：",df_judgement['内装'].unique())

外装： [0 5 4 3]
内装： [0 5 4 3]


In [ ]:
#鑑定日カラムを作成
df_judgement['鑑定日'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : x[-11:-1] if ('鑑定日' in x) else "0")
df_judgement['鑑定日'] = df_judgement['鑑定日'].str.translate(str.maketrans({"-":""}))
df_judgement['鑑定日'] = df_judgement['鑑定日'].astype('int')

df_judgement['鑑定日'].unique()

array([       0, 20210624, 20210715, 20210722, 20210611, 20210527,
       20210319, 20210119, 20210618, 20210416, 20210616, 20210723,
       20210609, 20210602, 20210521, 20210727, 20210721, 20210714,
       20210716, 20210708, 20210713, 20210706, 20210630, 20210622,
       20210617, 20210608, 20210604, 20210529, 20210520, 20210420,
       20210421, 20210414, 20210331, 20210705, 20210318, 20210428,
       20210330, 20210511, 20210603, 20210729, 20210720, 20210402,
       20210430, 20210709, 20210526, 20210601, 20210513, 20210126,
       20210429, 20210719, 20210419, 20210707, 20210525, 20210728,
       20210615, 20210610, 20210730, 20210518, 20210205, 20210702,
       20210427, 20210415, 20210423, 20210309, 20210209, 20210105,
       20201006, 20200921, 20201214, 20210528, 20210412, 20210401,
       20210304, 20210512, 20210122, 20200612, 20210623, 20210514,
       20201216, 20201013, 20210510, 20210303, 20210317, 20210629,
       20210607, 20210703, 20210726, 20210628, 20210625, 20210

In [ ]:
#ID車両(グー鑑定)カラムを削除
del df_judgement['ID車両(グー鑑定)']
df_judgement.head(1)

ページ                   車名     価格            総額        色            年式  \
0  27129593  タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）  パールブラック  令和3年(2021年)    

  走行距離   地域       車検  修復歴 未使用車 ワンオーナー 禁煙車  \
0  3km  北海道  2024/01    0    −      ○   ○   

                                                  保証 ミッション 駆動方式    排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD  660cc  5ドア   

  乗車定員    燃料   ハンドル      車台番号    記録簿 リサイクル料     整備 全長 全幅 全高 車両重量 燃費 使用燃料  \
0   4名  ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別  法定整備付                         

                                               オプション  外装  内装  鑑定日  
0  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...   0   0    0

In [ ]:
def judgement_preprocessing(df_judgement):
    df_judgement['修復歴'] = 0
    for num, name in enumerate(['無','軽度','中度','重度']):
        df_judgement['修復歴'] = df_judgement['修復歴'].mask(df_judgement['ID車両(グー鑑定)'].str.contains(name), num+1)
        
    df_judgement['外装'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : int(x[3:4]) if ('鑑定日' in x) else 0)

    df_judgement['内装'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : int(x[8:9]) if ('鑑定日' in x) else 0)
    
    df_judgement['鑑定日'] = df_judgement['ID車両(グー鑑定)'].map(lambda x : x[-11:-1] if ('鑑定日' in x) else "0")
    df_judgement['鑑定日'] = df_judgement['鑑定日'].str.translate(str.maketrans({"-":""}))
    df_judgement['鑑定日'] = df_judgement['鑑定日'].astype('int')
    
    del df_judgement['ID車両(グー鑑定)']
    

In [ ]:
#テスト
df_judgement = df.copy()
judgement_preprocessing(df_judgement)
for name in ['修復歴','外装','内装','鑑定日']:
    print(name,"：",df_judgement[name].unique())
df_judgement.head(1)

修復歴 ： [0 1 3 2 4]
外装 ： [0 5 4 3]
内装 ： [0 5 4 3]
鑑定日 ： [       0 20210624 20210715 20210722 20210611 20210527 20210319 20210119
 20210618 20210416 20210616 20210723 20210609 20210602 20210521 20210727
 20210721 20210714 20210716 20210708 20210713 20210706 20210630 20210622
 20210617 20210608 20210604 20210529 20210520 20210420 20210421 20210414
 20210331 20210705 20210318 20210428 20210330 20210511 20210603 20210729
 20210720 20210402 20210430 20210709 20210526 20210601 20210513 20210126
 20210429 20210719 20210419 20210707 20210525 20210728 20210615 20210610
 20210730 20210518 20210205 20210702 20210427 20210415 20210423 20210309
 20210209 20210105 20201006 20200921 20201214 20210528 20210412 20210401
 20210304 20210512 20210122 20200612 20210623 20210514 20201216 20201013
 20210510 20210303 20210317 20210629 20210607 20210703 20210726 20210628
 20210625 20210621 20210614 20210517 20210712 20210519 20210410 20210405
 20210329 20210310 20210325 20210701 20200710 20210531 20200516 202003

ページ                   車名     価格            総額        色            年式  \
0  27129593  タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）  パールブラック  令和3年(2021年)    

  走行距離   地域       車検  修復歴 未使用車 ワンオーナー 禁煙車  \
0  3km  北海道  2024/01    0    −      ○   ○   

                                                  保証 ミッション 駆動方式    排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD  660cc  5ドア   

  乗車定員    燃料   ハンドル      車台番号    記録簿 リサイクル料     整備 全長 全幅 全高 車両重量 燃費 使用燃料  \
0   4名  ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別  法定整備付                         

                                               オプション  外装  内装  鑑定日  
0  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...   0   0    0

## 全長・全幅・全高・車両重量・燃費

In [ ]:
df_length = df.copy()
df_length['全長'].value_counts()

3,395mm※1    30392
              8283
3,995mm※1     1467
4,740mm※1      606
4,935mm※1      601
3,700mm※1      574
4,100mm※1      497
4,760mm※1      441
4,265mm※1      421
4,770mm※1      398
4,800mm※1      372
4,710mm※1      369
3,840mm※1      353
3,760mm※1      325
4,290mm※1      285
4,235mm※1      279
4,690mm※1      270
4,495mm※1      260
4,540mm※1      258
3,710mm※1      251
4,180mm※1      249
4,950mm※1      246
3,705mm※1      242
3,725mm※1      241
4,545mm※1      239
4,840mm※1      239
4,360mm※1      230
4,695mm※1      223
3,790mm※1      211
4,600mm※1      211
4,395mm※1      209
3,940mm※1      194
4,295mm※1      183
5,340mm※1      163
3,660mm※1      159
4,060mm※1      156
3,650mm※1      155
4,460mm※1      154
4,275mm※1      153
4,910mm※1      149
4,065mm※1      147
4,610mm※1      144
4,900mm※1      133
4,915mm※1      126
3,550mm※1      125
4,375mm※1      123
3,990mm※1      116
3,720mm※1      114
3,680mm※1      112
4,260mm※1      105
3,890mm※1      103
4,825mm※1      101
4,400mm※1   

In [ ]:
df_width = df.copy()
df_width['全幅'].value_counts()

1,475mm※1    30393
              8282
1,695mm※1     4658
1,670mm※1     1336
1,795mm※1     1252
1,850mm※1     1156
1,855mm※1      996
1,760mm※1      674
1,840mm※1      628
1,625mm※1      515
1,800mm※1      499
1,740mm※1      407
1,665mm※1      399
1,885mm※1      374
1,765mm※1      353
1,645mm※1      324
1,790mm※1      308
1,735mm※1      291
1,820mm※1      286
1,745mm※1      279
1,880mm※1      249
1,805mm※1      217
1,770mm※1      205
1,865mm※1      194
1,730mm※1      187
1,725mm※1      161
1,775mm※1      156
1,895mm※1      149
1,825mm※1      136
1,835mm※1      116
1,860mm※1      109
1,900mm※1      109
1,810mm※1      103
1,660mm※1       99
1,830mm※1       76
1,780mm※1       69
1,845mm※1       67
1,750mm※1       65
1,875mm※1       64
1,930mm※1       54
1,690mm※1       52
1,890mm※1       44
1,870mm※1       39
1,815mm※1       37
1,970mm※1       33
1,905mm※1       33
1,715mm※1       31
1,935mm※1       25
1,920mm※1       24
1,785mm※1       24
2,020mm※1       22
1,980mm※1       21
1,650mm※1   

In [ ]:
df_height = df.copy()
df_height['全高'].value_counts()
#3つともmm※1で終わっている
#同じ処理でまとめられないか

             8282
1,630mm※1    3444
1,785mm※1    3425
1,650mm※1    2658
1,500mm※1    2521
1,790mm※1    2348
1,680mm※1    2085
1,755mm※1    1773
1,525mm※1    1586
1,780mm※1    1531
1,655mm※1    1514
1,475mm※1    1278
1,640mm※1    1229
1,735mm※1    1164
1,800mm※1    1085
1,660mm※1     981
1,620mm※1     963
1,835mm※1     807
1,675mm※1     732
1,600mm※1     724
1,775mm※1     691
1,745mm※1     646
1,815mm※1     631
1,880mm※1     583
1,705mm※1     566
1,550mm※1     559
1,725mm※1     497
1,825mm※1     490
1,690mm※1     490
1,710mm※1     475
1,470mm※1     469
1,865mm※1     449
1,875mm※1     431
1,530mm※1     402
1,455mm※1     399
1,515mm※1     390
1,850mm※1     387
1,610mm※1     386
1,520mm※1     368
1,540mm※1     365
1,590mm※1     325
1,510mm※1     315
1,460mm※1     299
1,605mm※1     290
1,435mm※1     289
1,730mm※1     262
1,935mm※1     246
1,665mm※1     243
2,105mm※1     216
1,545mm※1     216
1,685mm※1     208
1,840mm※1     203
1,750mm※1     199
1,430mm※1     187
1,445mm※1     178
1,885mm※1 

In [ ]:
#もしかしたらlwhwfにできるかも
df_weight = df.copy()
df_weight['車両重量'].value_counts()

             8312
900kg※1      2605
830kg※1      2101
850kg※1      1965
920kg※1      1916
840kg※1      1897
820kg※1      1866
650kg※1      1722
890kg※1      1424
880kg※1      1349
910kg※1      1296
770kg※1      1278
950kg※1      1257
810kg※1      1223
970kg※1      1046
870kg※1      1040
930kg※1       789
670kg※1       725
1,000kg※1     694
940kg※1       656
960kg※1       615
860kg※1       608
1,350kg※1     606
980kg※1       601
680kg※1       582
1,080kg※1     569
790kg※1       524
1,030kg※1     524
1,020kg※1     508
720kg※1       490
2,010kg※1     419
1,070kg※1     387
750kg※1       381
1,320kg※1     376
1,570kg※1     341
1,620kg※1     330
1,090kg※1     328
1,440kg※1     319
1,600kg※1     293
1,960kg※1     286
1,970kg※1     274
990kg※1       268
1,630kg※1     261
1,210kg※1     260
2,080kg※1     257
1,680kg※1     254
1,100kg※1     233
1,010kg※1     229
1,040kg※1     227
1,360kg※1     227
1,370kg※1     225
1,180kg※1     220
800kg※1       220
1,610kg※1     220
1,060kg※1     212
1,220kg※1 

In [ ]:
df_fuelconsumption = df.copy()
df_fuelconsumption['燃費'].value_counts()

              14420
27.2km/L※1     2432
31.0km/L※1     2178
27.0km/L※1     2081
30.0km/L※1     1981
28.2km/L※1     1878
30.4km/L※1     1719
28.6km/L※1     1499
25.4km/L※1     1219
26.4km/L※1     1163
25.7km/L※1     1065
37.0km/L※1      998
29.4km/L※1      983
35.2km/L※1      838
22.8km/L※1      731
24.6km/L※1      687
22.0km/L※1      664
34.2km/L※1      663
13.6km/L※1      575
19.0km/L※1      534
26.8km/L※1      522
16.0km/L※1      520
29.0km/L※1      519
27.8km/L※1      518
25.2km/L※1      517
29.8km/L※1      476
24.8km/L※1      454
25.0km/L※1      446
28.0km/L※1      432
30.2km/L※1      404
23.4km/L※1      403
11.4km/L※1      402
27.4km/L※1      399
34.0km/L※1      393
25.6km/L※1      369
16.2km/L※1      349
23.8km/L※1      329
33.4km/L※1      305
35.6km/L※1      305
22.4km/L※1      299
37.2km/L※1      284
22.6km/L※1      279
32.2km/L※1      262
20.2km/L※1      260
15.4km/L※1      258
20.6km/L※1      244
21.2km/L※1      242
11.6km/L※1      224
16.4km/L※1      214
16.6km/L※1      200


In [ ]:
#一応全長において全ての必要な処理を記述してみる
df_length['全長'] = df_length['全長'].map(lambda x : x[:-4] if ("mm※1" in x) else "0")
df_length['全長'] = df_length['全長'].str.translate(str.maketrans({",":""}))
df_length['全長'] = df_length['全長'].astype('int')

df_length['全長'].unique()

array([   0, 3395, 4545, 4935, 3855, 4265, 4695, 4760, 4740, 4600, 4950,
       3790, 3760, 3890, 4800, 4710, 4450, 4755, 4330, 4915, 4180, 4610,
       4945, 4825, 4910, 3705, 4385, 4770, 5340, 3995, 4750, 4405, 4275,
       4095, 4840, 4500, 4160, 3700, 4690, 4455, 4280, 3550, 4350, 4870,
       4395, 4495, 3845, 5050, 5290, 3840, 4255, 4670, 4805, 5165, 5380,
       4520, 4790, 4605, 4640, 4120, 4460, 4360, 3710, 4100, 3660, 4065,
       3545, 3940, 4235, 4485, 4400, 4260, 4900, 4645, 4475, 4625, 4590,
       4075, 3720, 3725, 4535, 4815, 4115, 4200, 4240, 4295, 3990, 3680,
       4090, 3885, 4540, 4660, 4685, 3650, 4975, 4595, 3715, 3945, 4420,
       4340, 4725, 4375, 4655, 3630, 4060, 4735, 4930, 4190, 4470, 4720,
       4730, 4465, 4430, 4425, 4650, 4270, 4830, 4885, 4490, 3955, 4575,
       4045, 4290, 3825, 4480, 4250, 4785, 4325, 4940, 4040, 4410, 5335,
       4305, 4550, 4390, 5110, 4965, 4635, 4705, 4835, 4985, 5000, 5270,
       5060, 4515, 3980, 4370, 4675, 5065, 4865, 48

In [ ]:
def lwhwf_preprocessing(df_lwhwf):
    lwhwf_names = ["全長","全幅","全高","車両重量","燃費"]
    lwhwf_dtypes = ['int','int','int','int','float']
    for lwhwf_name,lwhwf_dtype  in zip(lwhwf_names,lwhwf_dtypes):
        df_lwhwf[lwhwf_name] = df_lwhwf[lwhwf_name].map(lambda x : x[:-4] if ("※" in str(x)) else "0")
        df_lwhwf[lwhwf_name] = df_lwhwf[lwhwf_name].str.translate(str.maketrans({",":"","k":"","m":""}))
        df_lwhwf[lwhwf_name] = df_lwhwf[lwhwf_name].astype(lwhwf_dtype)
    

In [ ]:
#テスト
df_lwhwf = df.copy()
lwhwf_preprocessing(df_lwhwf)
df_lwhwf.head(10)

ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検    修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01  修復歴なし    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06  修復歴なし    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03  修復歴なし    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07  修復歴なし    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01  修復歴なし    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06  修復歴なし    ○      −   −   

                                                  保証 ミッション 駆動方式     排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT  4WD   660cc  5ドア   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...   CVT  4WD   660cc  5ドア   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...    AT  4WD  2200cc  5ドア   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...   CVT  4WD   660cc  5ドア   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...   CVT  4WD   660cc  5ドア   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...   CVT  4WD   660cc  5ドア   

  乗車定員     燃料   ハンドル      車台番号    記録簿 リサイクル料                 整備  \
0   4名   ガソリン  右ハンドル  403（下3桁）  記録簿あり    リ済別              法定整備付   
1   4名   ガソリン  右ハンドル  786（下3桁）  記録簿あり    リ済別              法定整備付   
2   4名   ガソリン  右ハンドル  475（下3桁）  記録簿あり    リ済別              法定整備付   
3   4名   ガソリン  右ハンドル  583（下3桁）           リ済別             法定整備なし   
4   4名    その他  右ハンドル  892（下3桁）           リ済別             法定整備なし   
5   4名   ガソリン  右ハンドル  594（下3桁）           リ済別              法定整備付   
6   5名  ディーゼル  右ハンドル  654（下3桁）           リ済込             法定整備なし   
7   4名    その他  右ハンドル  641（下3桁）           リ済別  法定整備別（整備費19,800円）   
8   4名   ガソリン  右ハンドル  656（下3桁）  記録簿あり    リ済別              法定整備付   
9   4名    その他  右ハンドル  544（下3桁）           リ済別             法定整備なし   

                              ID車両(グー鑑定)    全長    全幅    全高  車両重量    燃費  \
0                                            0     0     0     0   0.0   
1                                         3395  1475  1655   970  27.4   
2                                            0     0     0     0   0.0   
3  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-06-24）  3395  1475  1815   960  25.4   
4  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-15）  3395  1475  1785   900  26.4   
5                                         3395  1475  1630   890  24.0   
6                                         4545  1840  1690  1680  17.2   
7                                         3395  1475  1680   860  27.8   
8  外装：5　内装：5　機関：正常　修復歴：無（鑑定日 2021-07-22）  3395  1475  1630   880  24.0   
9                                         3395  1475  1680   860  27.8   

      使用燃料                                 

## 使用燃料

In [ ]:
df_usingfuel = df.copy()
df_usingfuel['使用燃料'].value_counts()
#lwhwffにできない悔しさ

レギュラー※1    43912
            8398
ハイオク※1      2259
ディーゼル※1     2021
Name: 使用燃料, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
df_usingfuel['使用燃料'][df_usingfuel['使用燃料']==''] = "0"
LE_usingfuel = LabelEncoder()
LE_usingfuel.fit(df_usingfuel['使用燃料'])
df_usingfuel['使用燃料'] = LE_usingfuel.transform(df_usingfuel['使用燃料'])

print(LE_usingfuel.classes_)
df_usingfuel['使用燃料'].value_counts()

['0' 'ディーゼル※1' 'ハイオク※1' 'レギュラー※1']


3    43912
0     8398
2     2259
1     2021
Name: 使用燃料, dtype: int64

In [ ]:
def usingfuel_preprocessing(df_usingfuel):
    from sklearn.preprocessing import LabelEncoder
    df_usingfuel['使用燃料'][df_usingfuel['使用燃料']==''] = "0"
    global LE_usingfuel
    LE_usingfuel = LabelEncoder()
    LE_usingfuel.fit(df_usingfuel['使用燃料'])
    df_usingfuel['使用燃料'] = LE_usingfuel.transform(df_usingfuel['使用燃料'])
    

In [ ]:
#テスト
df_usingfuel = df.copy()
usingfuel_preprocessing(df_usingfuel)
print(LE_usingfuel.classes_)
df_usingfuel['使用燃料'].unique()

['0' 'ディーゼル※1' 'ハイオク※1' 'レギュラー※1']


array([0, 3, 1, 2])

## データ前処理　最終関数2

In [ ]:
def kkkcom_preprocessing_under(df):
    mission_preprocessing(df)
    drive_preprocessing(df)
    displacement_preprocessing(df)
    door_preprocessing(df)
    capacity_preprocessing(df)
    fuel_preprocessing(df)
    handle_preprocessing(df)
    number_preprocessing(df)
    record_preprocessing(df)
    recycle_preprocessing(df)
    maintenance_preprocessing(df)
    judgement_preprocessing(df)
    lwhwf_preprocessing(df)
    usingfuel_preprocessing(df)
    

In [ ]:
#テスト
df_under = df.copy()
kkkcom_preprocessing_under(df_under)
df_under.head(10)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


ページ                     車名     価格            総額                  色  \
0  27129593    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）            パールブラック   
1  27121735  ムーヴキャンバス ＧホワイトアクセントＶＳ  160.0  （総額 166.6万円）         ブルーミングピンクＭ   
2  27121713    タント カスタムＸスタイルセレクション  178.0  （総額 184.5万円）      シャイニングホワイトパール   
3  26844930                Ｎ−ＢＯＸ Ｌ  156.7  （総額 167.4万円）       プラチナホワイト・パール   
4  26490416          スペーシア ハイブリッドＧ  119.7  （総額 130.3万円）   アーバンブラウンパールメタリック   
5  26282556               ムーヴ カスタム  170.2  （総額 177.2万円）             パールマイカ   
6  26105257                ＣＸ−５ ＸＤ  317.8  （総額 342.0万円）  スノーフレイクホワイトパールマイカ   
7  27096885           ハスラー ハイブリッドＧ  142.0                          クールカーキー   
8  27081191           ムーヴ ＸリミテッドＩＩ  133.0  （総額 139.6万円）      シャイニングホワイトパール   
9  27052930           ハスラー ハイブリッドＧ  151.0  （総額 157.7万円）            パールホワイト   

             年式 走行距離   地域       車検  修復歴 未使用車 ワンオーナー 禁煙車  \
0  令和3年(2021年)   3km  北海道  2024/01    0    −      ○   ○   
1  令和3年(2021年)   3km  北海道  2024/01    0    −      ○   ○   
2  令和3年(2021年)   3km  北海道  2024/01    0    −      ○   ○   
3  令和3年(2021年)   3km  北海道  2024/06    1    −      −   ○   
4  令和3年(2021年)   3km  北海道  2024/03    1    ○      −   ○   
5  令和3年(2021年)   3km  北海道  2024/03    0    ○      −   −   
6  令和3年(2021年)   3km  北海道  2024/07    0    ○      −   ○   
7  令和3年(2021年)   4km  北海道  2024/06    0    −      −   −   
8  令和3年(2021年)   4km  北海道  2024/01    1    −      ○   ○   
9  令和3年(2021年)   4km  北海道  2024/06    0    ○      −   −   

                                                  保証  ミッション  駆動方式   排気量  ドア数  \
0  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2     4   660    5   
1  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2     4   660    5   
2  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2     4   660    5   
3  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2     4   660    5   
4  販売店保証付(無料保証 期間:3ヵ月 距離:3,000km ※いずれかの条件に達するまで保証...      2     4   660    5   
5  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2     4   660    5   
6  販売店保証付(無料保証 期間:3ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用い...      1     4  2200    5   
7  販売店保証付(無料保証 期限:2026年6月 距離:100,000km ※いずれかの条件に達...      2     4   660    5   
8  販売店保証付(無料保証 期間:12ヵ月 距離:無制限 ※いずれかの条件に達するまで保証を適用...      2     4   660    5   
9  販売店保証付(無料保証 期限:2024年6月 距離:60,000km ※いずれかの条件に達す...      2     4   660    5   

   乗車定員  燃料  ハンドル  車台番号  記録簿  リサイクル料    全長    全幅    全高  車両重量    燃費  使用燃料  \
0     4   1     0   403    1       1     0     0     0     0   0.0     0   
1     4   1     0   786    1       1  3395  1475  1655   970  27.4     3   
2     4   1     0   475    1       1     0     0     0     0   0.0     0   
3     4   1     0   583    0       1  3395  1475  1815   960  25.4     3   
4     4   0     0   892    0       1  3395  1475  1785   900  26.4     3   
5     4   1     0   594    0       1  3395  1475  1630   890  24.0     3   
6     5   2     0   654    0       2  4545  1840  1690  1680  17.2     1   
7     4   0     0   641    0       1  3395  1475  1680   860  27.8     3   
8     4   1     0   656    1       1  3395  1475  1630   880  24.0     3   
9     4   0     0   544    0       1  3395  1475  1680   860  27.8     3   

                                               オプション  整備フラグ    整備費  外装  内装  \
0  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...      1      0   0   0   
1       エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS       1      0   0   0   
2  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS 両側...      1      0   0   0   
3  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS 盗難...      2      0   5   5   
4  エアコン パワーステアリング パワーウィンドウ カーナビ キーレスエントリー エアバッグ A...      2      0   5   5   
5  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS 盗難...      1      0   0   0   
6  エアコン パワーステアリング パワーウィンドウ カーナビ バックモニターカメラ テレビ CD...      2      0   0   0   
7  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS 盗難...      0  19800   0   0   
8  エアコン パワーステアリング パワーウィンドウ キーレスエントリー エアバッグ ABS ベン...      1      0   5   5   
9